// GENERATED by scripts/sync-widget-config.js from assets/themes/themes.json — do not edit by hand.
window.IDP_CONFIG = {
  "themes": {
    "lavender": {
      "soft": "#d9d5f5",
      "deep": "#b3a2c2",
      "tint": "#f2eff9"
    },
    "blue": {
      "soft": "#cedff0",
      "deep": "#96a7c3",
      "tint": "#eef4fa"
    },
    "green": {
      "soft": "#d1e8d3",
      "deep": "#9da482",
      "tint": "#eff7ef"
    },
    "pink": {
      "soft": "#dfabb7",
      "deep": "#cd9392",
      "tint": "#f8eaed"
    },
    "beige": {
      "soft": "#dacdc2",
      "deep": "#ae9986",
      "tint": "#f4efea"
    },
    "grey": {
      "soft": "#d5d5d5",
      "deep": "#bebab9",
      "tint": "#f1f1f0"
    },
    "peach": {
      "soft": "#ffd8c9",
      "deep": "#e9ab95",
      "tint": "#fff1eb"
    },
    "yellow": {
      "soft": "#f9e8b2",
      "deep": "#dcc274",
      "tint": "#fdf7e3"
    },
    "sky": {
      "soft": "#d8e8f7",
      "deep": "#9fbbd8",
      "tint": "#f0f6fc"
    }
  },
  "neutrals": {
    "paper": "#fcfcf9",
    "ink": "#4a4a4a",
    "sub": "#9a9a96",
    "line": "#d9d9d4",
    "icon_dark": "#e6e6e3"
  },
  "defaults": {
    "theme": "green",
    "mode": "light",
    "border": "card",
    "radius": 18,
    "weekStart": "mon"
  },
  "commonParams": [
    "theme",
    "soft",
    "deep",
    "mode",
    "border",
    "radius",
    "bg",
    "weekStart"
  ]
};
